// Generated by CoffeeScript 1.10.0

/*
Copyright 2016 Clemens Nylandsted Klokmose, Aarhus University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */
$(document).ready((function(_this) {
  return function() {
    var doc, ready, webstrate, ws, wshost;
    webstrate = window.location.pathname.slice(1, +window.location.pathname.length + 1 || 9e9);
    document.title = "Webstrate - " + webstrate;
    if (webstrate.length === 0) {
      throw "Error: No webstrate id provided";
    }
    wshost = 'ws://' + window.location.host + '/ws/';
    ws = new ReconnectingWebSocket(wshost);
    window._sjs = new sharejs.Connection(ws);
    doc = _sjs.get('webstrates', webstrate);
    doc.subscribe();
    ready = false;
    setTimeout((function() {
      if (!ready) {
        return $('body').append("Loading...");
      }
    }), 500);
    return doc.whenReady(function() {
      $(document).empty();
      ready = true;
      return window.dom2shareInstance = new DOM2Share(doc, document, function() {
        var domain, event, referrerDomain;
        document.dispatchEvent(new CustomEvent("loaded"));
        window.loaded = true;
        if (parent === window) {
          return;
        }
        parent.postMessage("loaded", '*');
        referrerDomain = util.extractDomain(document.referrer);
        domain = util.extractDomain(location.href);
        if (referrerDomain !== domain) {
          return;
        }
        if (window.frameElement != null) {
          event = new CustomEvent("transcluded", {
            detail: {
              name: webstrate
            },
            bubbles: true,
            cancelable: true
          });
          return window.frameElement.dispatchEvent(event);
        }
      });
    });
  };
})(this));

//# sourceMappingURL=client.js.map
